#!/usr/bin/env python3
"""Internal link checker for the payai-docs Mintlify site.

Resolves every internal link found in .mdx sources against:
  - actual page files (.mdx -> route path)
  - actual asset files (images, svg, etc.)
  - docs.json navigation entries
Reports links that resolve to nothing.
"""
import json, re, sys, pathlib, collections

ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent)

# ---- build the set of valid routes ----------------------------------------
pages = set()
for p in ROOT.rglob("*.mdx"):
    if "node_modules" in p.parts or p.name.startswith("_"):
        continue
    rel = p.relative_to(ROOT).with_suffix("")
    pages.add("/" + str(rel))
    if rel.name == "index":
        pages.add("/" + str(rel.parent))

assets = set()
for ext in ("png","jpg","jpeg","svg","gif","webp","pdf","json","txt","ico"):
    for p in ROOT.rglob(f"*.{ext}"):
        if "node_modules" in p.parts or ".git" in p.parts:
            continue
        assets.add("/" + str(p.relative_to(ROOT)))

nav_pages = set()
def walk_nav(node):
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "pages" and isinstance(v, list):
                for it in v:
                    if isinstance(it, str):
                        nav_pages.add("/" + it)
                    else:
                        walk_nav(it)
            else:
                walk_nav(v)
    elif isinstance(node, list):
        for v in node: walk_nav(v)

docsjson = json.loads((ROOT/"docs.json").read_text())
walk_nav(docsjson.get("navigation", {}))
redirects = {r["source"]: r["destination"] for r in docsjson.get("redirects", [])}

valid = pages | assets | nav_pages | set(redirects)

# ---- extract links ---------------------------------------------------------
MD  = re.compile(r'\]\((/[^)\s]*)\)')
JSX = re.compile(r'href="(/[^"]*)"')

broken = collections.defaultdict(list)
total = 0
for p in sorted(ROOT.rglob("*.mdx")):
    if "node_modules" in p.parts: continue
    text = p.read_text()
    rel = str(p.relative_to(ROOT))
    for m in list(MD.finditer(text)) + list(JSX.finditer(text)):
        raw = m.group(1)
        total += 1
        target = raw.split("#")[0].split("?")[0].rstrip("/")
        if not target:      # pure anchor like (#section)
            continue
        if target in valid or target + "/index" in valid:
            continue
        # .md variants of real pages (agent-facing) are generated by Mintlify
        if target.endswith(".md") and target[:-3] in valid:
            continue
        broken[rel].append(raw)

print(f"scanned {total} internal links across {len(list(ROOT.rglob('*.mdx')))} mdx files")
print(f"valid routes known: {len(pages)} pages, {len(assets)} assets, {len(redirects)} redirects\n")

if not broken:
    print("✓ no broken internal links")
    sys.exit(0)

n = sum(len(v) for v in broken.values())
print(f"✗ {n} broken internal link(s) in {len(broken)} file(s):\n")
for f, links in sorted(broken.items()):
    print(f"  {f}")
    for l in sorted(set(links)):
        print(f"      {l}")
sys.exit(1)
