#!/usr/bin/env python3
"""Internal link checker for the payai-docs Mintlify site.

Resolves every internal link found in .mdx sources against:
  - actual page files (.mdx -> route path)
  - actual asset files (images, svg, etc.)
  - local docs.json redirects (including their destinations)
Also checks that navigation entries name real pages.
"""
import json, re, sys, pathlib, collections
from urllib.parse import urljoin, urlsplit, unquote

ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent)

# ---- build the set of valid routes ----------------------------------------
pages = set()
for p in ROOT.rglob("*.mdx"):
    if "node_modules" in p.parts or p.name.startswith("_"):
        continue
    rel = p.relative_to(ROOT).with_suffix("")
    pages.add("/" + str(rel))
    if rel.name == "index":
        pages.add("/" + str(rel.parent))

assets = set()
for ext in ("png","jpg","jpeg","svg","gif","webp","pdf","json","txt","ico"):
    for p in ROOT.rglob(f"*.{ext}"):
        if "node_modules" in p.parts or ".git" in p.parts:
            continue
        assets.add("/" + str(p.relative_to(ROOT)))

nav_pages = set()
def walk_nav(node):
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "pages" and isinstance(v, list):
                for it in v:
                    if isinstance(it, str):
                        nav_pages.add("/" + it)
                    else:
                        walk_nav(it)
            else:
                walk_nav(v)
    elif isinstance(node, list):
        for v in node: walk_nav(v)

docsjson = json.loads((ROOT/"docs.json").read_text())
walk_nav(docsjson.get("navigation", {}))
redirects = {r["source"]: r["destination"] for r in docsjson.get("redirects", [])}

valid = pages | assets | set(redirects)

# ---- extract links ---------------------------------------------------------
MD  = re.compile(r'\]\(([^)\s]+)\)')
JSX = re.compile(r"""href=["']([^"']+)["']""")

broken = collections.defaultdict(list)
total = 0
for target in sorted(nav_pages - pages):
    broken["docs.json navigation"].append(target)
def internal_target(raw, rel):
    if raw.startswith("#"):
        return None  # Fragment existence requires rendered-heading verification.
    base = "https://docs.payai.network/" + str(pathlib.PurePosixPath(rel).with_suffix(""))
    parsed = urlsplit(urljoin(base, raw))
    if parsed.scheme not in ("http", "https") or parsed.netloc != "docs.payai.network":
        return None
    return unquote(parsed.path).rstrip("/")

def exists(target):
    if not target:
        return True  # Site root, not an independently rendered-page check.
    return (target in pages or target in assets or target + "/index" in pages
            or (target.endswith(".md") and target[:-3] in pages))

for source in redirects:
    target, seen = source, set()
    while target in redirects and target not in seen:
        seen.add(target)
        target = internal_target(redirects[target], target.lstrip("/"))
        if target is None:  # External redirect; not network-verified here.
            break
    if target is not None and (target in seen or not exists(target)):
        broken["docs.json redirects"].append(source + " -> " + str(target))

for p in sorted(ROOT.rglob("*.mdx")):
    if "node_modules" in p.parts: continue
    # Code examples are not rendered links.
    text = re.sub(r"\x60\x60\x60.*?\x60\x60\x60", "", p.read_text(), flags=re.S)
    rel = str(p.relative_to(ROOT))
    for m in list(MD.finditer(text)) + list(JSX.finditer(text)):
        raw = m.group(1)
        target = internal_target(raw, rel)
        if target is None:
            continue
        total += 1
        if not target:      # pure anchor like (#section)
            continue
        if target in valid or target + "/index" in valid:
            continue
        # .md variants of real pages (agent-facing) are generated by Mintlify
        if target.endswith(".md") and target[:-3] in valid:
            continue
        broken[rel].append(raw)

# ---- llms.txt: served verbatim to agents, so its URLs must resolve too ------
llms = ROOT / "llms.txt"
llms_listed = set()
if llms.exists():
    for m in re.finditer(r'https://docs\.payai\.network(/[^)\s]*)', llms.read_text()):
        raw = m.group(1)
        total += 1
        target = raw.split("#")[0].rstrip("/")
        if not target:
            continue
        probe = target[:-3] if target.endswith(".md") else target
        if probe not in valid:
            broken["llms.txt"].append(raw)
        llms_listed.add(probe)
    # The file is hand-ordered, so a new nav page must be added to it by hand.
    for target in sorted(nav_pages - llms_listed):
        broken["llms.txt (nav page not listed)"].append(target)

print(f"scanned {total} internal links across {len(list(ROOT.rglob('*.mdx')))} mdx files + llms.txt")
print(f"valid routes known: {len(pages)} pages, {len(assets)} assets, {len(redirects)} redirects\n")
print("Scope: local path/nav/redirect existence; rendered fragments and external URLs are not verified.\n")

if not broken:
    print("✓ no broken internal links")
    sys.exit(0)

n = sum(len(v) for v in broken.values())
print(f"✗ {n} broken internal link(s) in {len(broken)} file(s):\n")
for f, links in sorted(broken.items()):
    print(f"  {f}")
    for l in sorted(set(links)):
        print(f"      {l}")
sys.exit(1)
